### ISSUE TITLE
Can't find function "rowMax" when running classifyTarget(return.probs=T)

### ISSUE THREAD

**Issue by bab2155** [igrabski/scRNAseq-cell-type#2]
When trying to get a probability matrix from `classifyTarget`, it can't find the funciton "rowMax"

``` r
> target_probs = classifyTarget(target, fit, other=T, return.probs = T)
Error in rowMax(probs) : could not find function "rowMax"
```

running `classifyTarget(target, fit, other=T)` does not throw an error.

**Comment by igrabski** [comment]
Thanks for bringing this to my attention! I have made an edit to the code, and it should now run without having to load any additional dependencies. Please let me know if the issue persists.

**Comment by bab2155** [comment]
Works now. Thanks for quick update!
